### ISSUE TITLE
Hi I am facing trouble in running tail sample program 

### ISSUE THREAD

**Issue by SamuelPark** [chrissainty/blazor-in-action#26]
Hi 
I am reading your book "Blazor in Action" and running sample code from my desktop 
But after 4 chapter running sample code is broken.  
I am working on Window 11 Pro and VS 2022 Pro.
 
Error from dev console in chrome shows belows 
```
blazor.webassembly.js:1 
        
       crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1[[BlazingTrails.Shared.Features.Home.Shared.GetTrailsRequest.Response, BlazingTrails.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1[[BlazingTrails.Shared.Features.Home.Shared.GetTrailsRequest.Response, BlazingTrails.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[Response](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[Response](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[Response](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.<ReadAllAsync>d__65`1[[BlazingTrails.Shared.Features.Home.Shared.GetTrailsRequest.Response, BlazingTrails.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Net.Http.Json.HttpContentJsonExtensions.<ReadFromJsonAsyncCore>d__4`1[[BlazingTrails.Shared.Features.Home.Shared.GetTrailsRequest.Response, BlazingTrails.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Net.Http.Json.HttpClientJsonExtensions.<GetFromJsonAsyncCore>d__13`1[[BlazingTrails.Shared.Features.Home.Shared.GetTrailsRequest.Response, BlazingTrails.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at BlazingTrails.Client.Features.Home.Shared.GetTrailsHandler.Handle(GetTrailsRequest request, CancellationToken cancellationToken) in D:\Blazor\blazor-in-action-main\blazor-in-action-main\chapter-08\BlazingTrails\BlazingTrails.Client\Features\Home\Shared\GetTrailsHandler.cs:line 20
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.<Handle>d__2[[BlazingTrails.Shared.Features.Home.Shared.GetTrailsRequest, BlazingTrails.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[BlazingTrails.Shared.Features.Home.Shared.GetTrailsRequest.Response, BlazingTrails.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.<Handle>d__2[[BlazingTrails.Shared.Features.Home.Shared.GetTrailsRequest, BlazingTrails.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[BlazingTrails.Shared.Features.Home.Shared.GetTrailsRequest.Response, BlazingTrails.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.<Handle>d__2[[BlazingTrails.Shared.Features.Home.Shared.GetTrailsRequest, BlazingTrails.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[BlazingTrails.Shared.Features.Home.Shared.GetTrailsRequest.Response, BlazingTrails.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.<Handle>d__2[[BlazingTrails.Shared.Features.Home.Shared.GetTrailsRequest, BlazingTrails.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[BlazingTrails.Shared.Features.Home.Shared.GetTrailsRequest.Response, BlazingTrails.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.<Handle>d__2[[BlazingTrails.Shared.Features.Home.Shared.GetTrailsRequest, BlazingTrails.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[BlazingTrails.Shared.Features.Home.Shared.GetTrailsRequest.Response, BlazingTrails.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.<Handle>d__2[[BlazingTrails.Shared.Features.Home.Shared.GetTrailsRequest, BlazingTrails.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[BlazingTrails.Shared.Features.Home.Shared.GetTrailsRequest.Response, BlazingTrails.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at BlazingTrails.Client.Features.Home.HomePage.OnInitializedAsync() in D:\Blazor\blazor-in-action-main\blazor-in-action-main\chapter-08\BlazingTrails\BlazingTrails.Client\Features\Home\HomePage.razor:line 70
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
window.Module.s.printErr @ blazor.webassembly.js:1
```

I guess there is something error get JSON data from API Server but I don't know how to get over this 
Please tell me how to run solution correctly

**Comment by dedalusmax** [comment]
the same..

**Comment by chrissainty** [comment]
Hi @SamuelPark and @dedalusmax.

Have you compared your code to the code in this repo for that chapter?

**Comment by JonanAA** [comment]
I have the same problem from Chapter 7 onwards. @chrissainty I tested your code from GitHub (Chapters 7 & 8) both failed with the same error. It seems like it's breaking on this line `return await _httpClient.GetFromJsonAsync<GetTrailsRequest.Response>(GetTrailsRequest.RouteTemplate);` in `GetTrailsHandler.cs`. Great book by the way!

**Comment by artsplunge** [comment]
Same issue here running Windows 10 w/VS 2022 Version 17.4.1.  I remember getting this error a while back and I can't remember what I had to do to correct.  Right now I'm taking the code straight out of the GitHub repository.  The error seems to occur from chapter-6 onwards.

**Comment by IK0VCK** [comment]
Hi @chrissainty, here the same but from  chapter 6.
>  Have you compared your code to the code in this repo for that chapter?
Also the code  from github produce the same error.

I've found the problem. The solution on github is set to run the client project when have to be the api project.
@chrissainty why do you not check your work ? 
there are other small errors and inconsistencies, it would be good if the code downloaded from github works without having to bugfix

**Comment by artsplunge** [comment]
I realize technical authors are very busy people who at times may have to piggyback writing a book on top of a full schedule of day work.  The book is written, it's sold and it would be nice to have some follow-up to questions that are asked in regards to making sample code that is provided in the book/Github to work properly.  I posted my original comment back on 11/21 and received no response.  I'm guessing there are others who have run into a similar issue (and it seems like someone found a fix in this thread) and have taken the time to figure out a solution or to be honest have not even run the sample code to know that a problem may exist.  I'm finally getting back into Blazor so I'll figure this out (I fixed it once before but can't remember what I did exactly).  Very disappointing approach to providing customer support.

**Comment by chrissainty** [comment]
@IK0VCK Startup projects aren't saved to the solution file, they are kept in the .suo file. A file that is not checked into source control. Also, the book clearly states that you need to make sure the API project is set to startup, at least twice actually. So please don't come here and make condescending comments when you clearly haven't done the most basic checks.

**Comment by chrissainty** [comment]
@artsplunge My apologies for not replying to your earlier comment. The application runs error free as far as I can see, the issues others have found all seem to come back to not having the API project set as the startup project. One other thing to check is that you have applied the migrations to the DB. If that doesn't fix the issue, I'll need some more information to go on as I can't see anything from my side right now.

**Comment by IK0VCK** [comment]
> @IK0VCK Startup projects aren't saved to the solution file, they are kept in the .suo file. A file that is not checked into source control. Also, the book clearly states that you need to make sure the API project is set to startup, at least twice actually. So please don't come here and make condescending comments when you clearly haven't done the most basic checks.

Sorry for my bad english.
My apologies for my too rude message. 
I've had the same issue of @SamuelPark @artsplunge and seeing that after a couple of month there is no answer, I gave an emotional response following the frustration I felt.
The day after, since the source of the problem was indeed trivial, I edit my message with:

> I've found the problem. The solution on github is set to run the client project when have to be the api project.
@chrissainty why do you not check your work ?
there are other small errors and inconsistencies, it would be good if the code downloaded from github works without having to bugfix

..,. my constructive contribution to help other readers to fix the problem (I edit my message before your replay to @artsplunge).

I find your book very interesting. The problems encountered by readers can be taken into consideration to add some small changes in future reprints.

@chrissainty Happy New Year, and thank you for publishing this book

**Comment by chrissainty** [comment]
I appreciate your reply @IK0VCK. 

I'm going to close this issue as I don't think there is anything outstanding here.
